export const Colors = {
  white: '#FFFFFF',
  black: '#000000',
  primary: '#5EC401',
  secondary: '#F37A20',
  green: '#5EC401',
  orange: '#F37A20',
  lightGray: '#869598',
  lightBlack: '#37474F',
  darkWhite: '#F0F1F2',
  darkGray: '#D9D9D9',
  red: '#FF5552',
};

export const Sizes = {
  // font sizes

  r1: 12,
  r2: 14,
  r3: 16,
  r4: 18,
  r5: 20,
  r6: 22,
  r7: 24,
  r8: 28,
  m1: 12,
  m2: 14,
  m3: 16,
  m4: 18,
  m5: 20,
  m6: 22,
  m7: 24,
  m8: 28,
  b1: 12,
  b2: 14,
  b3: 16,
  b4: 18,
  b5: 20,
  b6: 22,
  b7: 24,
  b8: 28,
  l1: 12,
  l2: 14,
  l3: 16,
  l4: 18,
  l5: 20,
  l6: 22,
  l7: 24,
  l8: 28,
  s1: 12,
  s2: 14,
  s3: 16,
  s4: 18,
  s5: 20,
  s6: 22,
  s7: 24,
  s8: 28,
};

export const Fonts = {
  r1: {fontSize: Sizes.r1, fontFamily: 'Poppins-Regular'},
  r2: {fontSize: Sizes.r2, fontFamily: 'Poppins-Regular'},
  r3: {fontSize: Sizes.r3, fontFamily: 'Poppins-Regular'},
  r4: {fontSize: Sizes.r4, fontFamily: 'Poppins-Regular'},
  r5: {fontSize: Sizes.r5, fontFamily: 'Poppins-Regular'},
  r6: {fontSize: Sizes.r6, fontFamily: 'Poppins-Regular'},
  r7: {fontSize: Sizes.r7, fontFamily: 'Poppins-Regular'},
  r8: {fontSize: Sizes.r8, fontFamily: 'Poppins-Regular'},
  s1: {fontSize: Sizes.s1, fontFamily: 'Poppins-SemiBold'},
  s2: {fontSize: Sizes.s2, fontFamily: 'Poppins-SemiBold'},
  s3: {fontSize: Sizes.s3, fontFamily: 'Poppins-SemiBold'},
  s4: {fontSize: Sizes.s4, fontFamily: 'Poppins-SemiBold'},
  s5: {fontSize: Sizes.s5, fontFamily: 'Poppins-SemiBold'},
  s6: {fontSize: Sizes.s6, fontFamily: 'Poppins-SemiBold'},
  s7: {fontSize: Sizes.s7, fontFamily: 'Poppins-SemiBold'},
  s8: {fontSize: Sizes.s8, fontFamily: 'Poppins-SemiBold'},
  m1: {fontSize: Sizes.m1, fontFamily: 'Poppins-Medium'},
  m2: {fontSize: Sizes.m2, fontFamily: 'Poppins-Medium'},
  m3: {fontSize: Sizes.m3, fontFamily: 'Poppins-Medium'},
  m4: {fontSize: Sizes.m4, fontFamily: 'Poppins-Medium'},
  m5: {fontSize: Sizes.m5, fontFamily: 'Poppins-Medium'},
  m6: {fontSize: Sizes.m6, fontFamily: 'Poppins-Medium'},
  m7: {fontSize: Sizes.m7, fontFamily: 'Poppins-Medium'},
  m8: {fontSize: Sizes.m8, fontFamily: 'Poppins-Medium'},
  b1: {fontSize: Sizes.b1, fontFamily: 'Poppins-Bold'},
  b2: {fontSize: Sizes.b2, fontFamily: 'Poppins-Bold'},
  b3: {fontSize: Sizes.b3, fontFamily: 'Poppins-Bold'},
  b4: {fontSize: Sizes.b4, fontFamily: 'Poppins-Bold'},
  b5: {fontSize: Sizes.b5, fontFamily: 'Poppins-Bold'},
  b6: {fontSize: Sizes.b6, fontFamily: 'Poppins-Bold'},
  b7: {fontSize: Sizes.b7, fontFamily: 'Poppins-Bold'},
  b7: {fontSize: Sizes.b7, fontFamily: 'Poppins-Bold'},
  l1: {fontSize: Sizes.l1, fontFamily: 'Poppins-Light'},
  l2: {fontSize: Sizes.l2, fontFamily: 'Poppins-Light'},
  l3: {fontSize: Sizes.l3, fontFamily: 'Poppins-Light'},
  l4: {fontSize: Sizes.l4, fontFamily: 'Poppins-Light'},
  l5: {fontSize: Sizes.l5, fontFamily: 'Poppins-Light'},
  l6: {fontSize: Sizes.l6, fontFamily: 'Poppins-Light'},
  l7: {fontSize: Sizes.l7, fontFamily: 'Poppins-Light'},
  l8: {fontSize: Sizes.l8, fontFamily: 'Poppins-Light'},
};

const appTheme = {Colors, Sizes, Fonts};

export default appTheme;
